# fly.toml app configuration file generated for viriya-mybuddy
#
# See https://fly.io/docs/reference/configuration/ for information

app = "mybuddytalk"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 18789
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  ROLE = "magician"
  GOG_GATEWAY_HOST = "[::]"
  GOG_GATEWAY_PORT = "18789"
  NODE_OPTIONS = "--max-old-space-size=1536"

[mounts]
  source = "emrys_data"
  destination = "/root/.clawdbot"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
